LiberacionProductoWeb/Controllers/AccessController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System;
using LiberacionProductoWeb.Models.ConfigViewModels;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Localization;
using LiberacionProductoWeb.Localize;
using Microsoft.AspNetCore.Identity;
using LiberacionProductoWeb.Models.IndentityModels;
using LiberacionProductoWeb.Helpers;

namespace LiberacionProductoWeb.Controllers
{
    public class AccessController : Controller
    {
        private readonly ILogger<AccessController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        IStringLocalizer<Resource> _resource;
        private readonly AccessOptions _accessOptions;

        public AccessController(ILogger<AccessController> logger, UserManager<ApplicationUser> userManager, IStringLocalizer<Resource> resource, AccessOptions accessOptions)
        {
            _logger = logger;
            _userManager = userManager;
            _resource = resource;
            _accessOptions = accessOptions;
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
        public async Task<IActionResult> Access()
        {
            ConfiguracionUsuarioVM configuracionUsuario = new ConfiguracionUsuarioVM();

            try
            {
                var userInfo = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
                configuracionUsuario.PathECB = _accessOptions.PathECB;
                configuracionUsuario.PathCAB = _accessOptions.PathCAB;
                configuracionUsuario.PathCPM = _accessOptions.PathCPM;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", _resource.GetString("ErrorPrincipal"));
                _logger.LogError(ex, "Error.");
            }

            return View(configuracionUsuario);
        }
    }
}

LiberacionProductoWeb/Controllers/CertCatalogosController.cs
using DevExpress.XtraReports.UI;
using LiberacionProducto.Entities.CertCatalogos;
using LiberacionProducto.Entities.Entities.CertCatalogos;
using LiberacionProducto.Services.Interfaces;
using LiberacionProductoWeb.Data;
using LiberacionProductoWeb.Data.Repository;
using LiberacionProductoWeb.Helpers;
using LiberacionProductoWeb.Mappers;
using LiberacionProductoWeb.Models.CertCatalogosViewModels;
using LiberacionProductoWeb.Models.IndentityModels;
using LiberacionProductoWeb.Services;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using RestSharp;
using RestSharp.Deserializers;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace LiberacionProductoWeb.Controllers
{
    public class CertCatalogosController : Controller
    {
        private readonly IAnalyticsCertsService _analyticsCerts;
        private readonly IGeneralCatalogRepository _generalRepository;
        private readonly IFormulaCatalogRepository _formulaRepository;
        private readonly IProductCatalogRepository _productRepository;
        private readonly IStabilityCatalogRepository _stabilityCatalogRepository;
        private readonly IContainerCatalogRepository _containerCatalogRepository;
        private readonly IDispositionCatalogRepository _dispositionCatalogRepository;
        private readonly IReportAuditTrailService _reportAuditTrailService;
        private readonly ILogger<AccessController> _logger;
        IStringLocalizer<Localize.Resource> _resource;
        private AppDbContext _context;
        private Transporte iD_GRADO;
        private readonly int[] plantsByUser;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IPrincipalService _principalService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly CatalogCertificate _catalogCertificate;
        private readonly ICertCatalogosService _certCatalogosService;

        public CertCatalogosController(ILogger<AccessController> logger, UserManager<ApplicationUser> userManager, IStringLocalizer<Localize.Resource> resource, IConfiguration config, CatalogCertificate catalogCertificate, ICertCatalogosService certCatalogosService)
        {
            _logger = logger;
            _userManager = userManager;
            _resource = resource;
            _config = config;
            _catalogCertificate = catalogCertificate;
            _certCatalogosService = certCatalogosService;
        }

        public IConfiguration _config { get; }

        [HttpGet]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
        public async Task<IActionResult> Catalogs()
        {
            Models.ConfigViewModels.ConfiguracionUsuarioVM configuracionUsuario = new Models.ConfigViewModels.ConfiguracionUsuarioVM();

            try
            {
                var userInfo = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", _resource.GetString("ErrorPrincipal"));
                _logger.LogError(ex, "Error.");
            }

            return View(configuracionUsuario);
        }

        #region GetAPI

        public List<Analizador> getAnalizador()
        {
            var _model = new List<Analizador>();
            var _url = _catalogCertificate.urlCatalogs + "Analizador";

            var client = new RestClient(_url);
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

            JsonDeserializer deserial = new JsonDeserializer();
            var JSONObj = deserial.Deserialize<Dictionary<string, string>>(response);

            _model = JsonConvert.DeserializeObject<List<Analizador>>(JSONObj["data"]);

            return _model;
        }

        public List<AnalizadorParametros> getAnalizadorParametros()
        {
            var _model = new List<AnalizadorParametros>();
            var _url = _catalogCertificate.urlCatalogs + "AnalizadorParam";

            var client = new RestClient(_url);
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

            JsonDeserializer deserial = new JsonDeserializer();
            var JSONObj = deserial.Deserialize<Dictionary<string, string>>(response);

            _model = JsonConvert.DeserializeObject<List<AnalizadorParametros>>(JSONObj["data"]);

            return _model.Where(x => x.iD_STATUS == 1).ToList();
        }

        public List<Clientes> getClientes()
        {
            var _model = new List<Clientes>();
            var _url = _catalogCertificate.urlCatalogs + "Cliente";

            var client = new RestClient(_url);
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

            JsonDeserializer deserial = new JsonDeserializer();
            var JSONObj = deserial.Deserialize<Dictionary<string, string>>(response);

            _model = JsonConvert.DeserializeObject<List<Clientes>>(JSONObj["data"]);

            return _model;
        }

        public List<EspecificacionDetalle> getEspecificacionDetalle()
        {
            var _model = new List<EspecificacionDetalle>();
            var _url = _catalogCertificate.urlCatalogs + "EspecificacionDetalle";

            var client = new RestClient(_url);
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

            JsonDeserializer deserial = new JsonDeserializer();
            var JSONObj = deserial.Deserialize<Dictionary<string, string>>(response);

            _model = JsonConvert.DeserializeObject<List<EspecificacionDetalle>>(JSONObj["data"]);

            return _model;
        }

        public List<EspecificacionMaster> getEspecificacionMaster()
        {
            var _model = new List<EspecificacionMaster>();
            var _url = _catalogCertificate.urlCatalogs + "EspecificacionMaster";

            var client = new RestClient(_url);
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

            JsonDeserializer deserial = new JsonDeserializer();
            var JSONObj = deserial.Deserialize<Dictionary<string, string>>(response);

            _model = JsonConvert.DeserializeObject<List<EspecificacionMaster>>(JSONObj["data"]);

            return _model;
        }

        public List<Grados> getGrado()
        {
            var _model = new List<Grados>();
            var _url = _catalogCertificate.urlCatalogs + "Grado";

            var client = new RestClient(_url);
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

            JsonDeserializer deserial = new JsonDeserializer();
            var JSONObj = deserial.Deserialize<Dictionary<string, string>>(response);

            _model = JsonConvert.DeserializeObject<List<Grados>>(JSONObj["data"]);

            return _model;
        }

        public List<Metodo> getMetodo()
        {
            var _model = new List<Metodo>();
            var _url = _catalogCertificate.urlCatalogs + "Metodo";

            var client = new RestClient(_url);
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

            JsonDeserializer deserial = new JsonDeserializer();
            var JSONObj = deserial.Deserialize<Dictionary<string, string>>(response);

            _model = JsonConvert.DeserializeObject<List<Metodo>>(JSONObj["data"]);

            return _model;
        }

        public List<Paises> getPaises()
        {
            var _model = new List<Paises>();
            var _url = _catalogCertificate.urlCatalogs + "Paises";

            var client = new RestClient(_url);
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

            JsonDeserializer deserial = new JsonDeserializer();
            var JSONObj = deserial.Deserialize<Dictionary<string, string>>(response);

            _model = JsonConvert.DeserializeObject<List<Paises>>(JSONObj["data"]);

            return _model;
        }

        public List<Parametro> getParametro()
        {
            var _model = new List<Parametro>();
            var _url = _catalogCertificate.urlCatalogs + "Parametro";

            var client = new RestClient(_url);
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

            JsonDeserializer deserial = new JsonDeserializer();
            var JSONObj = deserial.Deserialize<Dictionary<string, string>>(response);

            _model = JsonConvert.DeserializeObject<List<Parametro>>(JSONObj["data"]);

            return _model;
        }

        public List<Plantas> getPlantas()
        {
            var _model = new List<Plantas>();
            var _url = _catalogCertificate.urlCatalogs + "Planta";

            var client = new RestClient(_url);
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

LiberacionProductoWeb/Views/Access/Access.cshtml
@model LiberacionProductoWeb.Models.ConfigViewModels.ConfiguracionUsuarioVM;
@using Microsoft.Extensions.Localization;
@using LiberacionProductoWeb.Localize;
@using LiberacionProductoWeb.Helpers;
@using System.Globalization;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@inject IStringLocalizer<Resource> resource;

@{
	ViewData["Title"] = "Iconos de acceso";
	Layout = "~/Views/Shared/_LayoutAccess.cshtml";
}

<div class="section-container section-with-top-border p-b-10">
	<div class="row" style="text-align:center;">
		<div class="col-lg-12 m-b-15">
			@* <a href="@Model.PathECB" class="btn btn-blue" style="border-radius:10px"> *@
			<a href="@Url.Action("Clientes", "CertCatalogos")" class="btn btn-blue" style="border-radius:10px">
				<img src="~/img/access/especificaciones_de_clientes_bulk.png" alt="" style="width:25%; border-radius:10px" />
				Especificaciones de Clientes Bulk
			</a>
		</div>
	</div>
	<div class="row" style="text-align:center;">
		<div class="col-lg-12 m-b-15">
			@* <a href="@Model.PathCAB" class="btn btn-blue" style="border-radius:10px"> *@
			<a href="@Url.Action("Catalogs", "CertCatalogos")" class="btn btn-blue" style="border-radius:10px">
				<img src="~/img/access/certificados_analiticos_bulk.png" alt="" style="width:25%; border-radius:10px" />
				Certificados Analíticos Bulk
			</a>
		</div>
	</div>
	<div class="row" style="text-align:center;">
		<div class="col-lg-12 m-b-15">
			@* <a href="@Model.PathCPM" class="btn btn-blue" style="border-radius:10px"> *@
			<a href="@Url.Action("Index", "Home")" class="btn btn-blue" style="border-radius:10px">
				<img src="~/img/access/certificados_producto_medicinal_bulk.png" alt="" style="width:25%; border-radius:10px" />
				Certificados Producto Medicinal
			</a>
		</div>
	</div>
</div>

@section Styles {


	<link href="~/plugins/bootstrap-combobox/css/bootstrap-combobox.css" rel="stylesheet" />
	<link href="~/plugins/bootstrap-select/bootstrap-select.css" rel="stylesheet" />
	<link href="~/plugins/select2/dist/css/select2.min.css" rel="stylesheet" />
	<link href="~/plugins/bootstrap-calendar/css/bootstrap_calendar.css" rel="stylesheet" />


	<link href="~/plugins/DataTables/media/css/dataTables.bootstrap.min.css" rel="stylesheet" />
	<link href="~/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" rel="stylesheet" />
	<link href="~/plugins/DataTables/extensions/Buttons/css/buttons.bootstrap.min.css" rel="stylesheet" />

	<link href="~/plugins/gritter/css/jquery.gritter.css" rel="stylesheet" />

	<link href="~/plugins/jquery/jquery.dataTables.min.css" rel="stylesheet" />

}

@section scripts {

	<environment names="Development,Staging,Production">
		<script src="~/plugins/bootstrap-calendar/js/bootstrap_calendar.min.js"></script>

		<script src="~/plugins/gritter/js/jquery.gritter.js"></script>

		<script src="~/plugins/bootstrap-combobox/js/bootstrap-combobox.js"></script>
		<script src="~/plugins/bootstrap-select/bootstrap-select.js"></script>
		<script src="~/plugins/select2/dist/js/select2.min.js"></script>


		<script src="~/plugins/bootstrap-calendar/js/bootstrap_calendar.min.js"></script>

		<script src="~/plugins/DataTables/media/js/dataTables.bootstrap.min.js"></script>

		<script src="~/plugins/DataTables/media/js/jquery.dataTables.js"></script>
		<script src="~/plugins/DataTables/media/js/dataTables.bootstrap.min.js"></script>
		<script src="~/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js"></script>

		<script src="~/plugins/DataTables/extensions/Buttons/js/buttons.html5.min.js"></script>
		<script src="~/plugins/DataTables/extensions/Buttons/js/buttons.print.min.js"></script>
		<script src="~/plugins/DataTables/extensions/Buttons/js/dataTables.buttons.min.js"></script>

		<script src="~/plugins/gritter/js/jquery.gritter.js"></script>
		<script src="~/plugins/bootbox/js/bootbox.all.min.js"></script>

		<script src="~/js/demo.min.js"></script>
		<script src="~/js/apps.min.js"></script>
		<script src="~/js/catalogs.js"></script>
	</environment>

	<script>
		$(function () {

			if ('@Model.MensajeError'.length > 1) {
				$('#message').append('<div class="alert alert-danger"> <a class="close" data-dismiss="alert" href="#">&times;</a>@Model.MensajeError </div>');
			}
		});

		$(function () {

			if ('@Model.MensajeInfo'.length > 1) {
				$('#message').append('<div class="alert alert-success"> <a class="close" data-dismiss="alert" href="#">&times;</a>@Model.MensajeInfo </div>');
			}
		});

		$(document).ready(function () {

			App.init();
			Demo.init();
		});
	</script>
}